/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package navermapproject;

import navermapproject.view.MainScreen;

public class App {
    public static void main(String[] args) {
        new MainScreen();
    }
}
